export const PORTAL_AUTH_FIXTURES = Object.freeze({
  accounts: Object.freeze({
    studentActive: Object.freeze({
      portalAccountId: "acct_fixture_student_active",
      providerSubject: "fixture|student-active",
      status: "active",
      roles: Object.freeze(["student"]),
      displayName: "Fixture Student",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_student_001",
      verifiedCrmLink: true,
      privacyGateSatisfied: false,
    }),
    guardianActive: Object.freeze({
      portalAccountId: "acct_fixture_guardian_active",
      providerSubject: "fixture|guardian-active",
      status: "active",
      roles: Object.freeze(["guardian"]),
      displayName: "Fixture Guardian",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_guardian_001",
      verifiedCrmLink: true,
      privacyGateSatisfied: true,
    }),
    teacherActive: Object.freeze({
      portalAccountId: "acct_fixture_teacher_active",
      providerSubject: "fixture|teacher-active",
      status: "active",
      roles: Object.freeze(["teacher"]),
      displayName: "Fixture Teacher",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_teacher_001",
      verifiedCrmLink: true,
      privacyGateSatisfied: true,
    }),
    adminActive: Object.freeze({
      portalAccountId: "acct_fixture_admin_active",
      providerSubject: "fixture|admin-active",
      status: "active",
      roles: Object.freeze(["admin"]),
      displayName: "Fixture Admin",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_admin_001",
      verifiedCrmLink: true,
      privacyGateSatisfied: true,
      mfaRequired: true,
    }),
    disabledStudent: Object.freeze({
      portalAccountId: "acct_fixture_student_disabled",
      providerSubject: "fixture|student-disabled",
      status: "disabled",
      roles: Object.freeze(["student"]),
      displayName: "Disabled Fixture Student",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_student_disabled",
      verifiedCrmLink: true,
      privacyGateSatisfied: false,
    }),
    lockedStudent: Object.freeze({
      portalAccountId: "acct_fixture_student_locked",
      providerSubject: "fixture|student-locked",
      status: "locked",
      roles: Object.freeze(["student"]),
      displayName: "Locked Fixture Student",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_student_locked",
      verifiedCrmLink: true,
      privacyGateSatisfied: false,
    }),
    pendingInviteStudent: Object.freeze({
      portalAccountId: "acct_fixture_student_invited",
      providerSubject: null,
      status: "invited",
      roles: Object.freeze(["student"]),
      displayName: "Invited Fixture Student",
      preferredLanguage: "es",
      crmContactRef: "crm_contact_fixture_student_invited",
      verifiedCrmLink: false,
      privacyGateSatisfied: false,
    }),
    missingCrmLinkStudent: Object.freeze({
      portalAccountId: "acct_fixture_missing_crm_link",
      providerSubject: "fixture|missing-crm-link",
      status: "active",
      roles: Object.freeze(["student"]),
      displayName: "Fixture Missing Link",
      preferredLanguage: "es",
      crmContactRef: null,
      verifiedCrmLink: false,
      privacyGateSatisfied: false,
    }),
  }),
  students: Object.freeze({
    active: Object.freeze({
      crmContactRef: "crm_contact_fixture_student_001",
      sectionRefs: Object.freeze(["section_fixture_english_101"]),
    }),
    minor: Object.freeze({
      crmContactRef: "crm_contact_fixture_minor_001",
      sectionRefs: Object.freeze(["section_fixture_english_101"]),
    }),
    unrelated: Object.freeze({
      crmContactRef: "crm_contact_fixture_unrelated_001",
      sectionRefs: Object.freeze(["section_fixture_computing_201"]),
    }),
  }),
  guardianLinks: Object.freeze([
    Object.freeze({
      guardianPortalAccountId: "acct_fixture_guardian_active",
      studentCrmContactRef: "crm_contact_fixture_minor_001",
      accessLevel: "view_summary",
      consentStatus: "pending",
      linkStatus: "verified",
    }),
  ]),
  teacherAssignments: Object.freeze([
    Object.freeze({
      teacherPortalAccountId: "acct_fixture_teacher_active",
      sectionRef: "section_fixture_english_101",
      studentCrmContactRefs: Object.freeze([
        "crm_contact_fixture_student_001",
        "crm_contact_fixture_minor_001",
      ]),
    }),
  ]),
});
